name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    with:
      submodules: recursive
    steps:
    - uses: actions/checkout@v3
      
    - name: Build
      run: cc build.c -o build.x; ./build.x
